# Generated by Django 4.1.7 on 2023-02-24 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Dni')),
                ('dateJoined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('dateCreation', models.DateTimeField(auto_now=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('avatar', models.ImageField(null=True, upload_to='avatar/%Y/%m/%d')),
            ],
        ),
    ]
